project:
  type: website
  resources:
    - "www/" 
    - "assets/"
    - "images/"

website:
  title: "Gonçalo Matos"
  navbar:
    search: false
    right:
      - href: index.qmd
        text: Home
      - projects.qmd
      - publications.qmd
      - contacts.qmd
  page-footer: 
    left: "Developed with Quarto open-source publishing tool" 
    right: 
      - icon: github
        href: https://github.com/gmatosferreira/gmatosferreira

format:
  html:
    grid:
      body-width: 1180px
      margin-width: 120px
      sidebar-width: 240px
      gutter-width: 1.5rem
    theme:
      light: 
      - styles/theme-light.scss
    css: styles.css
    toc: false



