project:
  type: website
  resources:
    - "www/" 
    - "assets/"
    - "images/"

website:
  title: "Gonçalo Matos"
  navbar:
    search: false
    right:
      - href: index.qmd
        text: Home
      - projects.qmd
      - publications.qmd
      - contacts.qmd
  page-footer: 
    left: "Developed with Quarto open-source publishing tool" 
    right: 
      - icon: github
        href: https://github.com/gmatosferreira/gmatosferreira

format:
  html:
    theme:
      light: 
      - cosmo
      # cosmo, morph, lux, minty
    css: styles.css
    toc: false



